Company.create!([
  {name: "10Gen"},
  {name: "10 Speed Labs"},
  {name: "1800Postcards.com"},
  {name: "1938 News"},
  {name: "1stdibs.com"},
  {name: "2findLocal"},
  {name: "345 Design"},
  {name: "3Floz.com"},
  {name: "3rd Ward"},
  {name: "680 Partners LLC"},
  {name: "89 Second Productions"},
  {name: "8coupons"},
  {name: "9branding"},
  {name: "9mmedia"},
  {name: "A022 Digital"},
  {name: "ABLE Social"},
  {name: "AC Lion"},
  {name: "Acadaca"},
  {name: "Acceleron Digital"},
  {name: "ACE Portal Group"},
  {name: "Acquaintable"},
  {name: "AD60"},
  {name: "Adafruit Industries"},
  {name: "Adaptly"},
  {name: "Adcade"},
  {name: "adMarketplace"},
  {name: "Adore Me"},
  {name: "AdPrime Media"},
  {name: "AdRadar"},
  {name: "ADstruc"},
  {name: "AdTheorent"},
  {name: "Aggregift"},
  {name: "Agon Creative"},
  {name: "Agorafy"},
  {name: "AHALife"},
  {name: "Alchemy50"},
  {name: "Alexandria Center"},
  {name: "Align"},
  {name: "Alley Interactive"},
  {name: "AlleyNYC"},
  {name: "AlleyWatch"},
  {name: "Allmenus"},
  {name: "AlphaBoost"},
  {name: "ALTANOVA Energy+Sustainability"},
  {name: "Altruik"},
  {name: "AlumniChoose"},
  {name: "Amicus"},
  {name: "Ammirati"},
  {name: "Animoto"},
  {name: "Antarctic Creative"},
  {name: "Anvil+Gear"},
  {name: "Apartable"},
  {name: "Apogee Media"},
  {name: "AppAddictive"},
  {name: "Appboy, Inc."},
  {name: "Appetizer Mobile LLC"},
  {name: "AppFirst"},
  {name: "AppLaunch"},
  {name: "Applico"},
  {name: "AppNexus"},
  {name: "AppOrchard"},
  {name: "appssavvy"},
  {name: "Appular"},
  {name: "Appy Couple"},
  {name: "Arc90"},
  {name: "ArchetypeMe"},
  {name: "Architizer"},
  {name: "Arkadium"},
  {name: "ArtCycle"},
  {name: "ArtistUpgrade"},
  {name: "Artsicle"},
  {name: "Artspace"},
  {name: "Artsy"},
  {name: "ArxSocial"},
  {name: "Ashe Avenue"},
  {name: "Ataboy Studios"},
  {name: "Atavist"},
  {name: "Atlantic Metro"},
  {name: "Audiobrain"},
  {name: "Audioms"},
  {name: "AUDUBON"},
  {name: "Augmate"},
  {name: "Auxiliary Design Company"},
  {name: "Avalanche Studios"},
  {name: "Avec"},
  {name: "Aviary"},
  {name: "AxialMarket"},
  {name: "Balance Media, LLC"},
  {name: "Bandwidth Productions"},
  {name: "Bar & Club Stats"},
  {name: "BarkBox"},
  {name: "BaubleBar"},
  {name: "bContext"},
  {name: "BeenVerified"},
  {name: "Behance"},
  {name: "Berlin Cameron"},
  {name: "Bespoke Post"},
  {name: "BestVendor"},
  {name: "Betabeat"},
  {name: "Betaworks"},
  {name: "Betterfly"},
  {name: "Betterment"},
  {name: "Big Fuel Communications"},
  {name: "Big Human"},
  {name: "Big Spaceship"},
  {name: "BigTwist"},
  {name: "BioDigital"},
  {name: "Birchbox"},
  {name: "BiteHunter Corporation"},
  {name: "BitInstant LLC"},
  {name: "Bitly"},
  {name: "Bizbash Media"},
  {name: "Bizodo"},
  {name: "blacbocs"},
  {name: "Black Lapel"},
  {name: "Black Ocean"},
  {name: "BlankSlate"},
  {name: "Blenderbox"},
  {name: "Blip"},
  {name: "Blood, Sweat & Cheers"},
  {name: "Bloomberg"},
  {name: "Blue Fountain Media"},
  {name: "Blue Label Labs"},
  {name: "Blue Phoenix Media"},
  {name: "Blue Ridge Foundation"},
  {name: "Blue Telescope"},
  {name: "Bluum"},
  {name: "Bombfell"},
  {name: "Bondsy"},
  {name: "Bonobos"},
  {name: "Bonus.ly"},
  {name: "Bookish"},
  {name: "Boomset"},
  {name: "BOX Creative"},
  {name: "Boxee"},
  {name: "Brainscape"},
  {name: "Branch"},
  {name: "BRANDmini"},
  {name: "Brandt Works Inc."},
  {name: "Brightline"},
  {name: "Broadcastr"},
  {name: "Brooklyn Creative League"},
  {name: "Brooklyn Digital Foundry"},
  {name: "Brooklyn United"},
  {name: "BrunchCritic"},
  {name: "Buddy Media"},
  {name: "Bug Labs"},
  {name: "Building Link"},
  {name: "Built by the Factory"},
  {name: "Bundle"},
  {name: "Bunker New York"},
  {name: "Bureau Blank"},
  {name: "Business Insider"},
  {name: "BusinessReel"},
  {name: "BusinessWeek.com"},
  {name: "BustedTees"},
  {name: "BuyFolio"},
  {name: "BuzzFeed"},
  {name: "BuzzTable"},
  {name: "Byte Dept."},
  {name: "ByteFly, Inc."},
  {name: "Bytemark"},
  {name: "C-vibes"},
  {name: "C3 Metrics"},
  {name: "CabCorner LLC"},
  {name: "Campfire"},
  {name: "Canvas"},
  {name: "Capture Your Flag"},
  {name: "Car Part Kings"},
  {name: "Caravan Interactive"},
  {name: "CarePlanners"},
  {name: "Carrot Creative"},
  {name: "Cartoon Brew"},
  {name: "CASE"},
  {name: "Case Commons"},
  {name: "Catchafire"},
  {name: "Cellfish"},
  {name: "Chalkable"},
  {name: "ChallengePost"},
  {name: "charity: water"},
  {name: "charitybuzz"},
  {name: "ChartBeat"},
  {name: "Cheapism"},
  {name: "CheetahMail"},
  {name: "Chloe + Isabel"},
  {name: "Cinchcast"},
  {name: "CityMaps"},
  {name: "CityPockets"},
  {name: "Clear"},
  {name: "Clearhart Digital"},
  {name: "Clothes Horse"},
  {name: "Coalition for Queens"},
  {name: "Codecademy"},
  {name: "Collective[i]"},
  {name: "Collectrium"},
  {name: "Command C"},
  {name: "CommonBond"},
  {name: "Conductor, Inc"},
  {name: "Control Group"},
  {name: "CourseHorse"},
  {name: "Craft Coffee"},
  {name: "Crisp Media"},
  {name: "Crowdscore Labs Inc"},
  {name: "Crowdtap"},
  {name: "Cruiseline"},
  {name: "Curbed"},
  {name: "CyberCity"},
  {name: "Dash"},
  {name: "Datadog"},
  {name: "Datalot"},
  {name: "DataVelocity"},
  {name: "DateMySchool"},
  {name: "Daylife"},
  {name: "DealSurf"},
  {name: "Dear Seven"},
  {name: "Delivery.com"},
  {name: "Design Brooklyn"},
  {name: "Designer Pages"},
  {name: "Digital Brand Architects"},
  {name: "Digital Natives Group"},
  {name: "Digital Ocean"},
  {name: "Direct Agents"},
  {name: "Direct IQ"},
  {name: "DJ Booth"},
  {name: "Docracy"},
  {name: "DoesThatMakeSense.com"},
  {name: "DonorsChoose.org"},
  {name: "Doodle.ly"},
  {name: "Doormates, Inc."},
  {name: "DoSomething.org"},
  {name: "dotbox"},
  {name: "DOTGO"},
  {name: "Dropmark"},
  {name: "DugDug"},
  {name: "DUMBO Startup Lab"},
  {name: "DynamicOxygen"},
  {name: "EachScape"},
  {name: "EASTMEDIA"},
  {name: "Easy Pairings"},
  {name: "EasyBib.com"},
  {name: "Elite Daily"},
  {name: "Elucidate"},
  {name: "EnergyGridIQ"},
  {name: "EnergyHub"},
  {name: "Enertiv"},
  {name: "Enfatica"},
  {name: "Entrepreneurs Roundtable Accelerator "},
  {name: "Estimize"},
  {name: "Etsy"},
  {name: "EuroCheapo.com"},
  {name: "Eventava"},
  {name: "Event Now"},
  {name: "Everest BBN"},
  {name: "Everyone’s Mixtape"},
  {name: "Evidon"},
  {name: "Evol8tion"},
  {name: "Ex.fm"},
  {name: "Examville.com"},
  {name: "Expand The Room"},
  {name: "EXPO Communications"},
  {name: "EZTexting"},
  {name: "F & T Creative"},
  {name: "Fab"},
  {name: "FaithStreet"},
  {name: "Fancy Hands"},
  {name: "Fashion’s Collective"},
  {name: "Fashism"},
  {name: "Fathom"},
  {name: "fave Central"},
  {name: "Feengo"},
  {name: "Felt Tip Inc."},
  {name: "FiftyThree"},
  {name: "Find Your Lobster"},
  {name: "Findings"},
  {name: "Fine Print NYC"},
  {name: "Fino Consulting"},
  {name: "Fitango"},
  {name: "Fitocracy"},
  {name: "FitValet"},
  {name: "Flavorpill"},
  {name: "Float"},
  {name: "Flocabulary"},
  {name: "Floored"},
  {name: "Fluent"},
  {name: "Fog Creek"},
  {name: "Four32C"},
  {name: "Foursquare"},
  {name: "FranchiseHelp"},
  {name: "FreeDirectMedia.com"},
  {name: "Freelancers Union"},
  {name: "FreshDirect"},
  {name: "Freshplanet"},
  {name: "FriendsEAT"},
  {name: "Fueled"},
  {name: "Funding Gates"},
  {name: "Gallerama"},
  {name: "GameChanger"},
  {name: "Games for Change"},
  {name: "General Assembly"},
  {name: "Genesis Media"},
  {name: "GenR Media"},
  {name: "GetGlue"},
  {name: "GetVoIP"},
  {name: "gfreely"},
  {name: "Gift Hit"},
  {name: "Gilt"},
  {name: "GlobalPoint"},
  {name: "Goldbely"},
  {name: "Grade Spotter"},
  {name: "GramercyOne"},
  {name: "Greatist"},
  {name: "Group Commerce"},
  {name: "Grouper"},
  {name: "GroupMe"},
  {name: "Grovo"},
  {name: "GrowHack"},
  {name: "Gust"},
  {name: "H.Bloom"},
  {name: "Hackerati"},
  {name: "Handybook"},
  {name: "Happy"},
  {name: "Hara Partners"},
  {name: "Harvest"},
  {name: "HD Made"},
  {name: "Health Guru Media"},
  {name: "HealthiNation"},
  {name: "HOLSTEE"},
  {name: "Honest Buildings"},
  {name: "HookLogic"},
  {name: "HopSkoch"},
  {name: "HopStop"},
  {name: "Host Committee, Inc"},
  {name: "Hourly"},
  {name: "HowAboutWe.com"},
  {name: "HUGE"},
  {name: "Hunch"},
  {name: "Huntsy"},
  {name: "ICED Media"},
  {name: "IceHook Systems"},
  {name: "Icon Deposit"},
  {name: "Icreon"},
  {name: "Ideeli"},
  {name: "IDT Partners"},
  {name: "Immersive Labs"},
  {name: "Indaba Music"},
  {name: "Ingk Labs"},
  {name: "inSparq"},
  {name: "Integral Ad Science"},
  {name: "Intent Media"},
  {name: "INTRO Labs"},
  {name: "JIBE"},
  {name: "Jingle Punks Music"},
  {name: "JMT Apps"},
  {name: "JOOR"},
  {name: "Jun Group"},
  {name: "Jux"},
  {name: "JW Player"},
  {name: "JWT"},
  {name: "Kaltura"},
  {name: "Kapitall"},
  {name: "Kaptur"},
  {name: "Kapture"},
  {name: "Kargo"},
  {name: "KarmaBox"},
  {name: "Keep Holdings"},
  {name: "Kern+Lead"},
  {name: "Kikin"},
  {name: "Kiwi Interactive"},
  {name: "Kleverbeast"},
  {name: "Knack"},
  {name: "Knewton"},
  {name: "Knodes"},
  {name: "Know Your Meme"},
  {name: "Kohort"},
  {name: "Kollabora"},
  {name: "Kounterattack"},
  {name: "Krate"},
  {name: "Large Animal Games"},
  {name: "Launch.It"},
  {name: "Leadmotion"},
  {name: "Lean Startup Machine"},
  {name: "LearnVest"},
  {name: "Lenses RX"},
  {name: "Levo League"},
  {name: "Lifebooker"},
  {name: "Listen First Media"},
  {name: "littleBits"},
  {name: "LiveIntent"},
  {name: "LivePerson"},
  {name: "Livestream"},
  {name: "Local Bigwig"},
  {name: "Local Projects"},
  {name: "Local Response"},
  {name: "LocalVox Media"},
  {name: "Logicworks"},
  {name: "LongTail Video"},
  {name: "Lore"},
  {name: "Lot18"},
  {name: "Lover.ly"},
  {name: "Macabacus"},
  {name: "Mack Weldon"},
  {name: "Madison Logic"},
  {name: "Magnetic"},
  {name: "Magnify"},
  {name: "MakerBot Industries"},
  {name: "Maker’s Row"},
  {name: "Marathon Consulting"},
  {name: "Market Publique"},
  {name: "Marquee Media"},
  {name: "Mashable"},
  {name: "Mashwork"},
  {name: "MauroNewMedia"},
  {name: "Mazel Moments"},
  {name: "Media6Degrees"},
  {name: "mediabistro"},
  {name: "Medialets"},
  {name: "MediaMath"},
  {name: "Medtel"},
  {name: "MeeGenius, Inc"},
  {name: "Meetup"},
  {name: "Metronome3"},
  {name: "MileWise"},
  {name: "Mimeo"},
  {name: "Mindbug"},
  {name: "Minus"},
  {name: "Mirror"},
  {name: "Mixel"},
  {name: "MLB Advanced Media, L.P."},
  {name: "Mobile Commons"},
  {name: "Mobile Universal"},
  {name: "Mode Collective"},
  {name: "MongoDB"},
  {name: "Moonit"},
  {name: "Movable Ink"},
  {name: "Moveline"},
  {name: "Moven"},
  {name: "Mr. Youth"},
  {name: "Muck Rack"},
  {name: "Musicsoft Arts"},
  {name: "Music Xray"},
  {name: "MyBankTracker"},
  {name: "MyBillRegistry"},
  {name: "MyCityWay"},
  {name: "MyClean"},
  {name: "MyFreeConcert"},
  {name: "Naked Apartments"},
  {name: "Namely"},
  {name: "Nano Web Group"},
  {name: "Neighborhoodr"},
  {name: "Nerve"},
  {name: "Nest New York"},
  {name: "Nestio"},
  {name: "Netlan Technology Center"},
  {name: "Netmining"},
  {name: "Netted"},
  {name: "NetX"},
  {name: "Neuronic Games"},
  {name: "Never Liked It Anyway"},
  {name: "Neverware"},
  {name: "New Work City"},
  {name: "New York Digital Design"},
  {name: "New York eHealth"},
  {name: "New York Technology Council"},
  {name: "New York Startup Lab"},
  {name: "NewlyWish"},
  {name: "News.me"},
  {name: "NewsBlur"},
  {name: "NewsLook"},
  {name: "Next Big Sound"},
  {name: "Next Jump"},
  {name: "NextCustomer"},
  {name: "Nexxite"},
  {name: "NIFTIT"},
  {name: "Night Agency"},
  {name: "Night Owl Interactive"},
  {name: "Nimbo"},
  {name: "Nirvana Solutions"},
  {name: "nLytics"},
  {name: "Nodejitsu"},
  {name: "Noise"},
  {name: "Nomad Editions"},
  {name: "Nomorerack.com Inc."},
  {name: "Noodle"},
  {name: "Noom"},
  {name: "NorthPoint"},
  {name: "NoSQL Weekly"},
  {name: "Now"},
  {name: "NowThis News"},
  {name: "nrelate"},
  {name: "NSONE"},
  {name: "numberFire"},
  {name: "nuOctave, Inc."},
  {name: "NY Convergence"},
  {name: "NY Tech Meetup"},
  {name: "NYC Digital"},
  {name: "NYC Media Lab"},
  {name: "NYC Resistor"},
  {name: "nylmedia"},
  {name: "NYTechWomen"},
  {name: "NYU Polytech Incubator – DUMBO"},
  {name: "NYU Polytech Incubator – Varick Street"},
  {name: "Oberon Media"},
  {name: "oddcast"},
  {name: "Odyl"},
  {name: "Of a Kind"},
  {name: "OfferPop"},
  {name: "offMetro.com"},
  {name: "Offside"},
  {name: "Oh My! Me Studios"},
  {name: "OK Cupid"},
  {name: "OKFocus"},
  {name: "OK Venue"},
  {name: "Olapic"},
  {name: "OLO"},
  {name: "Omegapoint Inc."},
  {name: "OMGPOP"},
  {name: "Omnigon Communications"},
  {name: "On Deck Capital"},
  {name: "OnCom Digital Media"},
  {name: "One Art World"},
  {name: "One Hundred Robots"},
  {name: "One Nine Studios"},
  {name: "OneBeat"},
  {name: "Onepager"},
  {name: "OnePublic"},
  {name: "OneWire"},
  {name: "OnSwipe"},
  {name: "Ontodia"},
  {name: "ooVoo"},
  {name: "OpenFin"},
  {name: "OpenGeo"},
  {name: "OpenPlans"},
  {name: "OpenSky"},
  {name: "Operative Media"},
  {name: "Opt-Intelligence Inc."},
  {name: "Optimize New York"},
  {name: "OrangeYouGlad"},
  {name: "OrderGroove"},
  {name: "ordr.in"},
  {name: "Organic Motion"},
  {name: "Organized Wisdom"},
  {name: "Originet"},
  {name: "outgrow.me"},
  {name: "Oyster"},
  {name: "PacerMonitor"},
  {name: "Panelfly"},
  {name: "Paperless Post"},
  {name: "Paperlex"},
  {name: "PaperTrail"},
  {name: "Paperwhite Studio"},
  {name: "Park Hudson International"},
  {name: "Parse.ly"},
  {name: "Partnership for New York City Fund"},
  {name: "Patch"},
  {name: "Patentory"},
  {name: "Patron Technology"},
  {name: "PayPerks"},
  {name: "Payz.com"},
  {name: "PC Dudes"},
  {name: "Peek"},
  {name: "PeekYou"},
  {name: "Peer39"},
  {name: "Peeriscope"},
  {name: "Penguin Digital"},
  {name: "Pensa"},
  {name: "PercentMobile"},
  {name: "Percepted"},
  {name: "Percolate"},
  {name: "Perka"},
  {name: "Permission Data"},
  {name: "Personal Democracy Forum"},
  {name: "Phase Four Media"},
  {name: "PhotoShelter"},
  {name: "Phreesia"},
  {name: "PickiPicki"},
  {name: "Pictorious"},
  {name: "Piictu"},
  {name: "Pilot.is"},
  {name: "Pipture"},
  {name: "Pixable"},
  {name: "Pixafy"},
  {name: "Pixelittle"},
  {name: "Pixel NYC"},
  {name: "PlaceIQ, Inc."},
  {name: "Playground Group"},
  {name: "Playground Sessions"},
  {name: "pledge4good, LLC"},
  {name: "Plethora Mobile"},
  {name: "Plyfe"},
  {name: "Pod1"},
  {name: "PolicyMic"},
  {name: "Pond5"},
  {name: "Pontiflex"},
  {name: "Portable"},
  {name: "Poshly"},
  {name: "Postable"},
  {name: "PostHelpers"},
  {name: "Postling"},
  {name: "Poutsch"},
  {name: "POV (The American Documentary Inc.)"},
  {name: "Powerhead Games"},
  {name: "Powhow Inc."},
  {name: "Pradux"},
  {name: "Prehype"},
  {name: "Pricetag"},
  {name: "Pricing Engine"},
  {name: "PrivCo"},
  {name: "Profitably"},
  {name: "Project Aurora Games"},
  {name: "Project Noah"},
  {name: "Project One"},
  {name: "Projective Space"},
  {name: "Projeqt"},
  {name: "Prolific Interactive"},
  {name: "Promediacorp"},
  {name: "Pronto"},
  {name: "ProperCloth"},
  {name: "ProPublica"},
  {name: "Proust"},
  {name: "PSFK"},
  {name: "PublicStuff"},
  {name: "PublicTrades"},
  {name: "PulsePoint"},
  {name: "Punch!"},
  {name: "Punkle"},
  {name: "PureWow"},
  {name: "Purpose"},
  {name: "Pushkart"},
  {name: "QFive"},
  {name: "QLabs"},
  {name: "Quantum Networks"},
  {name: "Quartz"},
  {name: "Quirky"},
  {name: "Qwiki"},
  {name: "R/GA"},
  {name: "Radio Tag"},
  {name: "Rainbow Broadband Inc"},
  {name: "Rallyverse"},
  {name: "Rap Genius"},
  {name: "Raygun"},
  {name: "Rayogram"},
  {name: "Readability"},
  {name: "ReadSocial"},
  {name: "Real Capital Analytics"},
  {name: "Real Data Management"},
  {name: "RealDirect"},
  {name: "Reboot"},
  {name: "Reclip.It"},
  {name: "reComparison"},
  {name: "RecordSetter"},
  {name: "Recyclebank"},
  {name: "Red Antler"},
  {name: "Red Baron Technologies"},
  {name: "Red Paper Heart"},
  {name: "Red Rover"},
  {name: "Refined Hype"},
  {name: "Refinery29"},
  {name: "Remedy Systems"},
  {name: "Rent the Runway"},
  {name: "Rentenna"},
  {name: "RentHackr"},
  {name: "RentHop"},
  {name: "RentShare Inc"},
  {name: "Reputation Observer"},
  {name: "Resolute Digital"},
  {name: "ResponsiveAds"},
  {name: "Republic Spaces"},
  {name: "RetailMLS"},
  {name: "Revenue Trades"},
  {name: "RevTrax"},
  {name: "Rewind.Me"},
  {name: "Ride the City"},
  {name: "RightsFlow"},
  {name: "Rip Road"},
  {name: "RobustLinks"},
  {name: "RocketHub"},
  {name: "ROI Payments"},
  {name: "ROKKAN"},
  {name: "Ronik "},
  {name: "RoomHints"},
  {name: "Routehappy"},
  {name: "Rozilo Inc"},
  {name: "RubbishBooks"},
  {name: "RUN"},
  {name: "Sailthru"},
  {name: "salido"},
  {name: "SamStella, LLC"},
  {name: "Sanborn Media Factory, Inc."},
  {name: "SankyNet"},
  {name: "Sarkissian Mason"},
  {name: "Sawhorse"},
  {name: "SayForExample, Inc"},
  {name: "Scanbuy"},
  {name: "scenyc, inc."},
  {name: "Schoology"},
  {name: "Sciplay, a wholly owned subsidiary of Scientific Games"},
  {name: "Scratch Interactive"},
  {name: "SCRATCH MUSIC GROUP"},
  {name: "ScrollMotion"},
  {name: "sdbase"},
  {name: "Seamless"},
  {name: "Seamless Receipts"},
  {name: "SeatGeek"},
  {name: "SecondMarket"},
  {name: "Secret Clubhouse, LLC"},
  {name: "SeedInvest, LLC"},
  {name: "Sefaira"},
  {name: "Select Office Suites"},
  {name: "Selectable Media"},
  {name: "Send Word Now"},
  {name: "Sense Networks"},
  {name: "Seven Rooms"},
  {name: "Shapeways"},
  {name: "She’s the First"},
  {name: "Shefinds.com aka SheFinds media"},
  {name: "Shelby.tv"},
  {name: "Sherpaa"},
  {name: "SheSpeaks"},
  {name: "Shift"},
  {name: "Shodogg"},
  {name: "Shootmap"},
  {name: "ShopKeep POS"},
  {name: "Shopography"},
  {name: "Shoptiques"},
  {name: "Shorefire Media"},
  {name: "Shorty Awards"},
  {name: "ShowMe"},
  {name: "ShowMeLocal Inc."},
  {name: "Shutterstock"},
  {name: "SideTour"},
  {name: "Sideways Inc."},
  {name: "Signasafe"},
  {name: "Signpost"},
  {name: "SimpleReach"},
  {name: "SimpleTexting"},
  {name: "SimplyEngage"},
  {name: "Simulmedia"},
  {name: "SinglePlatform"},
  {name: "SingWho"},
  {name: "Sinu"},
  {name: "Situation Interactive"},
  {name: "Skillcrush"},
  {name: "Skillshare"},
  {name: "Slader"},
  {name: "Slated"},
  {name: "SMAKK Studios"},
  {name: "Small Media Extra Large"},
  {name: "Small Planet Digital"},
  {name: "Smallknot"},
  {name: "SmartAsset"},
  {name: "Smartling"},
  {name: "Smith & Keller"},
  {name: "SnagFilms"},
  {name: "SNAP Interactive"},
  {name: "SnapGoods"},
  {name: "Snooth Media"},
  {name: "Social Amp"},
  {name: "Social Fresh"},
  {name: "Social Media Link"},
  {name: "Social Media Today"},
  {name: "Social Studies"},
  {name: "Socialbomb"},
  {name: "SocialFlow"},
  {name: "SocialGuide"},
  {name: "Socialistic"},
  {name: "Socialitical"},
  {name: "SocialQ"},
  {name: "Sociocast"},
  {name: "Solidoodle"},
  {name: "SomaComm"},
  {name: "Something Digital"},
  {name: "Sonar"},
  {name: "Songtrust"},
  {name: "Songza"},
  {name: "SortPrice"},
  {name: "Source4Style"},
  {name: "SpaFinder"},
  {name: "Speakaboos"},
  {name: "Special Applied Intelligence"},
  {name: "Splash"},
  {name: "Spling"},
  {name: "Sponsor Hub"},
  {name: "Sponsored Ads, Inc."},
  {name: "SponsorPitch.com"},
  {name: "Sportsvite"},
  {name: "Spotflux"},
  {name: "Spotfront"},
  {name: "SpotlessCity"},
  {name: "Springbase Media"},
  {name: "Squarespace"},
  {name: "Squeaky Wheel Media"},
  {name: "St. James Partners"},
  {name: "Stack Exchange"},
  {name: "Stackpop"},
  {name: "Startup Giraffe"},
  {name: "StarVest Partners"},
  {name: "State University of NY Downstate Medical Center Incubator"},
  {name: "STEADY"},
  {name: "Stealth Communications"},
  {name: "STELLAService"},
  {name: "Sterling Kane"},
  {name: "Stitch Collective"},
  {name: "stoopid jupiter"},
  {name: "Storyville"},
  {name: "Stray Boots"},
  {name: "StreetEasy"},
  {name: "StructuredWeb"},
  {name: "Studio Akko LLC"},
  {name: "Studio Mercury"},
  {name: "Studio One"},
  {name: "Style Coalition"},
  {name: "Style for Hire"},
  {name: "StyleCaster"},
  {name: "Stylitics"},
  {name: "Sub Rosa"},
  {name: "SubwayFunFinder.com"},
  {name: "Suddenlee"},
  {name: "Sulia"},
  {name: "SumAll"},
  {name: "SumZero"},
  {name: "Sunshine Suites"},
  {name: "Superglued"},
  {name: "Supertouch"},
  {name: "Svpply"},
  {name: "Swaag"},
  {name: "Sway Design"},
  {name: "Swayspace"},
  {name: "Swell"},
  {name: "Swiss Commerce"},
  {name: "SwoonNYC"},
  {name: "Tactic"},
  {name: "TagMan"},
  {name: "Take the Interview"},
  {name: "Take-Two Interactive"},
  {name: "talktala.com"},
  {name: "Tapad"},
  {name: "TapEdition"},
  {name: "Tapfame"},
  {name: "TapFury"},
  {name: "Targeted Social"},
  {name: "TargetSpot, Inc."},
  {name: "Tasklite / CPS Creative"},
  {name: "TaskStream"},
  {name: "TasteSavant"},
  {name: "Tattly"},
  {name: "Techonomy"},
  {name: "TechSpace"},
  {name: "Ted"},
  {name: "Tekserve"},
  {name: "Temboo"},
  {name: "Templar Studios"},
  {name: "TENDIGI"},
  {name: "Tenlegs"},
  {name: "Tenthwave"},
  {name: "TeuxDeux"},
  {name: "Thankster.com"},
  {name: "the {c}0dEd subsidiary of 140 Ventures"},
  {name: "The Atavist"},
  {name: "The Barbarian Group"},
  {name: "The Birdy Inc"},
  {name: "The Bosco"},
  {name: "The Chapter Media"},
  {name: "The Daily Beast"},
  {name: "The Digital Brand Architects"},
  {name: "The Fetch"},
  {name: "The Flatiron School"},
  {name: "The Game Agency"},
  {name: "The Harmony Institute"},
  {name: "The Hired Guns"},
  {name: "The Icon Deposit"},
  {name: "The JAR Group"},
  {name: "The Lascaux Company"},
  {name: "The Mechanism"},
  {name: "The Meta Agency"},
  {name: "The Metropolitan Exchange"},
  {name: "The Mindriot"},
  {name: "The Orchard"},
  {name: "The Smack Pack"},
  {name: "The Stashbox"},
  {name: "The Strategy Dept."},
  {name: "The SuperTouch Group"},
  {name: "The Unlimited Magazine"},
  {name: "The Webby Awards"},
  {name: "The Yard"},
  {name: "thefairgoer.com"},
  {name: "Thefuture.fm"},
  {name: "TheLadders"},
  {name: "Therefore Productions"},
  {name: "TheStreet"},
  {name: "ThinkBinder"},
  {name: "ThinkEco"},
  {name: "Thinkful"},
  {name: "Third Mind"},
  {name: "Third Wave Fashion"},
  {name: "This is Pop"},
  {name: "Three Ring"},
  {name: "Thrillist"},
  {name: "Thumb"},
  {name: "Thumbscribes"},
  {name: "Thuzio"},
  {name: "TickPick"},
  {name: "Tiger Party"},
  {name: "Timehop"},
  {name: "Tiny Mantis"},
  {name: "Tinypass"},
  {name: "Tip or Skip"},
  {name: "Tipping Point Partners"},
  {name: "TiqIQ"},
  {name: "ToBe"},
  {name: "Togather"},
  {name: "Tomorrow Lab"},
  {name: "Tomorrow Networks"},
  {name: "Topi"},
  {name: "TopMBACOnnect"},
  {name: "Totsy, Inc."},
  {name: "TouchGraph"},
  {name: "Toura"},
  {name: "Tracks"},
  {name: "TradeCard"},
  {name: "Transparensee"},
  {name: "Travel Tripper"},
  {name: "Travora Media"},
  {name: "Tremor Video"},
  {name: "Trendabl"},
  {name: "TreSensa"},
  {name: "Tribeca Digital"},
  {name: "TripleLift"},
  {name: "Troi.net"},
  {name: "Trusted Insight"},
  {name: "Truth NYC"},
  {name: "tumbleweed"},
  {name: "Tumblr"},
  {name: "TuneCore, Inc."},
  {name: "TuneSat"},
  {name: "TurboVote"},
  {name: "turntable.fm"},
  {name: "TurnTo Networks"},
  {name: "Tutorialize.me"},
  {name: "Tutorspree"},
  {name: "TwitrPix"},
  {name: "TxtImpact"},
  {name: "Tykoon"},
  {name: "Type/Code"},
  {name: "Überangst"},
  {name: "UberTags"},
  {name: "Umami"},
  {name: "Uncharted Play"},
  {name: "Uncommon Goods"},
  {name: "Under 30 CEO"},
  {name: "Undercurrent"},
  {name: "Underground Eats"},
  {name: "UNIFIED"},
  {name: "Unified Field"},
  {name: "Unigo"},
  {name: "Uniworld Group Inc."},
  {name: "Unpakt"},
  {name: "Unroll.me"},
  {name: "Updater"},
  {name: "UPlanMe"},
  {name: "UpSurge Media Group LLC"},
  {name: "Upworthy"},
  {name: "Urban Cargo"},
  {name: "Urban Compass"},
  {name: "Urban Daddy"},
  {name: "Urban Edge"},
  {name: "Urban Green Energy"},
  {name: "Urtak"},
  {name: "US Insurance"},
  {name: "Usablenet"},
  {name: "USL Technology Consulting"},
  {name: "Varick Media Management"},
  {name: "VaynerMedia"},
  {name: "Vector Media Group"},
  {name: "Vedanta Capital"},
  {name: "Velocidi"},
  {name: "Venmo"},
  {name: "VenueBook"},
  {name: "VFILES"},
  {name: "VHX"},
  {name: "Vice"},
  {name: "Vidaao Inc"},
  {name: "Viggle"},
  {name: "Villij"},
  {name: "Vimbly"},
  {name: "Vimeo"},
  {name: "Vindico"},
  {name: "Visual Goodness"},
  {name: "Visual Revenue"},
  {name: "Vivastream"},
  {name: "Vixely"},
  {name: "Vizalytics"},
  {name: "Vook"},
  {name: "Voxy"},
  {name: "VPV Interactive"},
  {name: "WaitAway"},
  {name: "Wakefield"},
  {name: "Wanderfly"},
  {name: "Warby Parker"},
  {name: "Warshaw Group"},
  {name: "Watch It"},
  {name: "Watchitoo"},
  {name: "WAVSYS"},
  {name: "Web Development Group NYC"},
  {name: "Webline Designs, Inc."},
  {name: "WebMediaBrands"},
  {name: "WebThriftStore"},
  {name: "WeCreateNYC"},
  {name: "Weduplay Inc."},
  {name: "Well + Good"},
  {name: "Wendr"},
  {name: "WeWork"},
  {name: "Whoisgreen.com"},
  {name: "Winfield & Co."},
  {name: "Winito Athletics"},
  {name: "Wiredset / Trendrr"},
  {name: "WNYC"},
  {name: "Work Market"},
  {name: "Worldwide Biggies"},
  {name: "Worry Free Labs"},
  {name: "Worstofall Design"},
  {name: "Wurku"},
  {name: "www.its-your-internet.com"},
  {name: "Wynter Consulting Group, LLC"},
  {name: "Xaxis"},
  {name: "xCubicle"},
  {name: "Xtify"},
  {name: "YAP Trackers"},
  {name: "Yapp"},
  {name: "YCharts"},
  {name: "YellowHammer Media"},
  {name: "Yext"},
  {name: "Yipit"},
  {name: "Yodle"},
  {name: "Yog"},
  {name: "YouAreTV"},
  {name: "YouGift"},
  {name: "YRB Magazine"},
  {name: "Zazoom LLC"},
  {name: "Zeel"},
  {name: "ZenCat Productions"},
  {name: "Zignage LLC"},
  {name: "Zipmark, Inc"},
  {name: "ZocDoc"}
])
Job.create!([
  {company: "Venmo", description: "The Manager, Mobile Growth will be part of our Business Development team, working directly with our sales and marketing and product and engineering teams -- to raise awareness and distribution of the combined Braintree / Venmo mobile capabilities amongst developers and their influencers", link: "http://www.ventureloop.com/greycroft/jobdetail.php?jobid=210384", title: "Manager, Mobile API Growth", category: "Engineering", sub_category: "Business Development", background: "engineering", experience_required: 2, full_text: nil, is_draft: nil, company_id: nil},
  {company: "Venmo", description: "We love making things, so our days are spent with our heads together, pondering the right things to make and how they should work. We huddle with engineers and work closely together on projects from end to end -- turning ideas into beautiful, simple, and lovable products that work well", link: "http://www.ventureloop.com/greycroft/jobdetail.php?jobid=210381", title: "Product Designer", category: "Design", sub_category: "Product Management", background: "design", experience_required: 2, full_text: nil, is_draft: nil, company_id: nil},
  {company: "Venmo", description: "Growth at Venmo is a an engineering - and analytics-driven function  Our Growth Engineering team implements new feature changes associated with acquiring and - or retaining users, then meticulously tracks and measures ensuing results. We are largely a full-stack team  - python, iOS, Android, Backbone/JS, etc", link: "http://www.ventureloop.com/greycroft/jobdetail.php?jobid=210380", title: "Growth Engineer", category: "Engineering", sub_category: "Growth Engineer", background: "engineering", experience_required: 2, full_text: nil, is_draft: nil, company_id: nil},
  {company: "LocalResponse", description: "LocalResponse is looking for an Account Manager to serve as the primary business contact for the client and who will be responsible for client satisfaction", link: "http://www.ventureloop.com/greycroft/jobdetail.php?jobid=196628", title: "Account Manager", category: "Sales", sub_category: "Account Management", background: "account management", experience_required: 2, full_text: "Greycroft About Portfolio Team Jobs Twitter Facebook RSS Jobs View all jobs Account Manager at LocalResponse New York City, NY, US Apply for this job LocalResponse is looking for an Account Manager to serve as the primary business contact for the client and who will be responsible for client satisfaction. The AM is expected to consistently provide excellent customer service to accounts, as well as represent client needs and goals within the organization to ensure quality. In addition, the AM will build relationships with clients to encourage new and repeat business opportunities. Responsibilities: Responsible for all client communications, conflict resolution, compliance on client deliverables and revenue Review all major deliverables to ensure quality standards and that client expectations are met Report to the VP, Director of Account Management, providing regular input on all account activity, including status and call reports on a weekly basis. Ensure that client issues are dealt with in an efficient manner, escalating to manager when needed Work closely with internal teams in order to maintain a continuous knowledge of account status in order to identify potential account issues and/or opportunities Ensure that all processes and procedures are completed, quality standards are met, and that campaigns are profitable Effectively communicate all company capabilities, services and offerings to the client Requirements: Proven Account Management skills required in order to create, maintain and enhance customer relationships Minimum 2 years of Account/project management experience Extremely detail oriented Technical competence (understand software, hardware, networks, etc) Motivated, goal oriented, persistent and a skilled negotiator High level of initiative and work well in a team environment Excellent written and verbal communication skills Handles stressful situations and deadlines well Plans and carries out responsibilities with minimal direction Undergraduate degree Apply for this job Careers Powered by VentureLoop - Portfolio Company Sign In ©2012 Greycroft Partners. All rights reserved. About Inquiries", is_draft: nil, company_id: nil}
])
Search.create!([
  {keywords: nil, category: "Engineering", experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: nil, experience: nil},
  {keywords: nil, category: "0", experience: 0},
  {keywords: nil, category: "0", experience: 0}
])
User.create!([
  {email: "test1@example.com", password_digest: "$2a$10$RM0NBX5Yfw9b0OvBqWW.G.gtjJASVocGRLWjfCTLOXctWV4T8QDwy", session_token: "-Pbxla44PnBopkM5juPI3g", job_settings: {}},
  {email: "guest1@gmail.com", password_digest: "$2a$10$0LBbrX1FvDiWDDfNE3a5LuFOLGnz1dM.1jZy.25.ULO/9BxGY1sB2", session_token: "f9WJZDHDt0_eq-RYW99w4g", job_settings: {"category"=>["Sales", "Engineering"]}},
  {email: "uciehlee@gmail.com", password_digest: "$2a$10$UJI1WAYRm7dqvARdxshnZuGqstoxzKbiYDSJAg2n42g6TZlB.ok3O", session_token: "ptjsLMQORpy1U3gB9J0cHA", job_settings: {}},
  {email: "guest@gmail.com", password_digest: "$2a$10$K3sHsC17V05CETGahO6TpemDvMKDfS/iPCzZdyq8nrxQ6FhYZABcq", session_token: "GkPHoiR1XHjiF2xOT9NH-g", job_settings: {"category"=>["Engineering", "Design"], "experience"=>["0"]}}
])
