class Taxonomy < ActiveRecord::Base
  
  def extract_level_and_base_title
    level = []
    
    Taxonomy.LEVELS.each do |lvl|
      level << lvl if self.title.match(/#{lvl}/i)
    end 

    if level.any?
      self.level = level.first
      self.base_title = self.title
      self.base_title.slice!(self.level)
      self.base_title.strip!
      self.save
    end
  end
  
  def self.to_csv
    CSV.generate do |csv|
      csv << column_names
      all.each do |product|
        csv << product.attributes.values_at(*column_names)
      end
    end
  end
    
  def self.set_dept
    Taxonomy.all.each do |taxonomy|
      self.dept_hash.each do |dept_key, roles_arr|
        roles_arr.each do |role|
          if taxonomy.title.match(/#{role}/i)
            taxonomy.dept = dept_key
            taxonomy.save
          end
        end
      end
    end 
  end
  
  def self.departments
    [
      # 'Administrative',
      # 'Bus. Development',
      'Design',
      'Engineering',
      # 'Finance, Accting',
      # 'Human Resources',
      # 'Legal',
      # 'Marketing',
      # 'Operations',
      # 'Product Management',
      # 'Project Management',
      # 'Sales'
    ]
  end
  
  
  
  # SCRATCH
  #-------------------------------------------------------
  
  def self.eng_hash 

  end

  def self.dept_hash
    {
      "account management" => [
        "account manager",
        'account executive',
        'account lead'
      ],
    
      "administrative" => [
        "office manager",
        "executive assistant",
        "office coordinator",
        "personal assistant",
        "receptionist",
        "administrative",
        'mail'
      ],
      
      "business analytics" => [
        'business analyst'
      ],
      
      "business development" => [
        'business development'
      ],
      
      "community" => [
        "community manager"
      ],
      
      "creative" => [
        "host",
        "producer"
      ],
      
      "customer service" => [
        'onboarding associate',
        'client support',
        'member experience',
        'member development'
      ],
      
      "content" => [
        "writer",
        "translator"
      ],
      
      "design" => [
        "ui",
        "ux",
        "graphic",
        "visual",
        'designer',
        'produce designer'
      ],
      
      "engineering" => [
        'technology lead',
        'software engineer',
        'engineer',
        'developer',
        'tech',
        'it'
      ],

      "events" => [
        'event',
        'events'
      ],
      
      "finance" => [
        "accounting",
        "accountant",
        "payroll"
      ],
      
      "growth" => [
        "user acquisition",
        "growth hacker"
      ],
      
      "human resources" => [
        "recruiter",
        "recruit",
        ' hr ',
        "human resources",
        'compensation',
        'hris',
        'hr '
      ],
      
      "legal" => [
        "counsel"
      ],
      
      "marketing" => [
        "marketing strategist",
        "digital marketing",
        "marketing analyst",
        "seo",
        "online marketing",
        "marketing specialist",
        "marketing manager",
        'head of marketing'
      ],
  
      "operations" => [
        'strategic operations',
        "operations associate",
        "sourcer",
        "operations specialist",
        'resource sourcing'
      ],
      
      "product" => [
        "product manager",
        "product analyst",
        "product management",
        'director of product'
      ],
      
      "project management" => [
        "project"
      ],
            
      "public relations" => [
        'public relations',
        'pr ',
        ' pr ',
        ' pr'
      ],
    
      "sales" => [
        'sales executive',
        'sales manager',
        'sales origination associate',
        'field associate',
        'director of national sales',
        'sales representative',
        'sales associate',
        'sales account',
        'sales executive',
        'sales lead',
        'enterprise sales'
      ],
      
      "strategy" => [
        "strategy associate"
      ] 
    }
  end

  def self.LEVELS
    [
      'analyst',
      'assistant',
      'associate',
      'chief',
      'director',
      'head',
      'intern',
      'lead',
      'national',
      'principal',
      'senior',
      'specialist',
      'vice president',
      'manager'
    ]
  end
  
  def self.ENGINEERING_TITLES
    [
      'Data Operations Associate',      
      'Automation Engineer',
      'Director of Engineering',
    ]
  end
  
  def self.RAW_TITLES 
    [
      'Assistant Office Manager',
      'Executive Assistant',
      'Office Coordinator',
      'Personal Assistant',
      'Business Development Director',
      'Front End Developer',
      'Lead Security Engineer',
      'Manual Quality Assurance Engineer',
      'Mobile Software Engineer',
      'Mobile Tech Lead',
      'Senior Dev Ops Engineer',
      'Senior Software Engineer',
      'Software Engineer',
      'Accounting Manager',
      'Finance & Strategy Associate',
      'Payroll Associate',
      'Senior Accountant',
      'Account Manager',
      'Inside Sales Executive',
      'Inside Sales Manager',
      'Onboarding Associate',
      'Practice Success Associate',
      'Sales Origination Associate',
      'IT Intern',
      'PR Intern',
      'Senior Network Engineer',
      'Technical Support Lead',
      'Associate Counsel',
      'Digital Marketing Strategist',
      'Director of Digital Marketing',
      'Doctor Marketing Specialist',
      'Writer / Translator',
      'Writer / Translator',
      'Writer / Translator',
      'Writer / Translator',
      'Writer / Translator',
      'Writer / Translator',
      'Writer / Translator',
      'Marketing Analyst',
      'Marketing Strategy Associate',
      'Public Relations Manager',
      'SEO Analyst',
      'Director of Strategic Operations',
      'Operations Associate',
      'Part Time Patient Operations Associate',
      'Part Time Patient Operations Associate - Spanish',
      'Technical Operations Associate',
      'Director of Product Management',
      'Product Analyst',
      'Product Manager',
      'Recruiting Coordinator',
      'Sales Recruiter',
      'Sourcer',
      'Tech Recruiter',
      'Sales Operations Analyst',
      'Sales Operations and Strategy Manager',
      'Sales Operations Field Associate',
      'Business Analyst Intern',
      'Strategic Account Manager',
      'Strategic Project Manager',
      'Strategic Sales Director',
      'Senior Software Engineer',
      'Accountant',
      'Host',
      'Producer',
      'Chief Human Resources Officer',
      'Compensation & HRIS Analyst',
      'Data Engineer',
      'Director of National Sales',
      'Director, YBN Product Performance',
      'IT Engineer- Network, Telecom, Systems',
      'Manager of Online Marketing Operations and Analysis',
      'Manager, Partner Marketing',
      'Marketing Operations Analyst',
      'National Account Manager',
      'Online Channel Marketing Manager',
      'Operations Associate Manager for Yodle for Brand Networks',
      'Operations Specialist',
      'Public Relations Manager',
      'Receptionist and Administrative Assistant',
      'Sales Representative',
      'Senior Software Engineer',
      'Senior Systems and DevOps Engineer',
      'Senior UI Engineer',
      'Software Engineer',
      'Systems and DevOps Engineer',
      'Technical Support Specialist',
      'Yipit Data Engineer',
      'Data Product Analyst',
      'Web Developer',
      'DevOps Engineer',
      'Frontend Engineer',
      'Implementation Engineer',
      'Senior Software Engineer',
      'Software Engineer',
      'Software Engineering Manager',
      'Account Director',
      'Account Manager',
      'Senior Sales Engineer',
      'Vice President, Enterprise Sales',
      'Client Support Specialist',
      'Enterprise Operations Specialist',
      'Software Engineer, Intern - Summer 2014',
      'SMB Sales Associate, University Graduate',
      'Enterprise Sales, Intern - Summer 2014',
      'Yext Sales Manager',
      'Yext Sales Associate',
      'Senior Product Manager',
      'Senior Account Executive',
      'Partner Developer',
      'Front-End Developer',
      'Web App Developer',
      'Developer Intern',
      'Web Engineer',
      'Head of UI/UX Design',
      'Marketing Intern',
      'Analyst',
      'Senior Analyst',
      'Director, TV Analytics',
      'Account Manager - General Submission',
      'Associate - General Submission',
      'Analyst, Audience Campaign Management - General Submission',
      'Internship (unpaid)',
      'Serious Software Engineer',
      'Enterprise Sales Executive',
      'Serious Backend Software Engineer',
      'Test Engineer',
      'Support and User Acquisition',
      'Marketing Intern',
      'Client Executive/Account Manager',
      'Inside Sales Executive',
      'Account Executive - House Accounts',
      'Professional Services Manager',
      'Resource Sourcing Manager',
      'Senior Editor',
      'Advertising Sales Account Manager',
      'Operations Assistant',
      'Associate Community Manager',
      'Construction Project Manager',
      'Director of Space Development',
      'Event Sales Coordinator',
      'HR Manager',
      'iOS Developer',
      'Mail Service Associate',
      'Member Experience Manager',
      'New Member Development Associate',
      'Ruby Developer',
      'Senior Community Manager / City Lead NYC',
      'UX/UI Designer',
      'Videographer & Editor',
      'WordPress Developer',
      'Editorial Intern',
      'Events Interns',
      'Technical Intern',
      'Freelance Writers',
      'Sales',
      'Commercial Counsel',
      'Financial Analyst',
      'Facilities Manager',
      'Head of Product',
      'Customer Experience Associate',
      'Spring PR Intern',
      'Head of Global Sourcing and Supply Chain',
      'Facilities Manager',
      'Optician',
      'Advisor - Part Time',
      'Optometrist',
      'Director, Tech Ops',
      'Principal Software Engineer, e-Commerce',
      'Software Engineer',
      'Infrastructure Engineer',
      'Software Engineer, Data Science',
      'Retail Support Engineer',
      'Project Manager, Systems Development',
      'Principal Software Engineer, Core Services',
      'Senior Software Engineer',
      'Automation Engineer',
      'Technology Intern',
      'Junior Software Engineer',
      'Back Office Engineer',
      'Data Scientist',
      'Front-End Developer',
      'Spring 2014 Interns',
      'Mobile Application Developer',
      'Senior Software Engineer',
      'Marketing Director',
      'Front End Engineer',
      'Back End Engineer',
      'Dev Ops Engineer',
      'Sales Executive',
      'UI Designer',
      'Front-End Developer',
      'Business Development Intern',
      'Social Media Specialist Intern',
      'Director, Business Development - Creator Platform',
      'Head of Content Strategy & Business Development',
      'Moderation Manager',
      'Hadoop Engineer',
      'Designer, Mobile Web',
      'Talent Network',
      'Corporate Counsel',
      'Manager, Marketing Analytics',
      'Director, Product Management - Audience',
      'Senior iOS Engineer',
      'Senior Mobile Project Manager',
      'Front-End Engineer (PHP / JavaScript)',
      'Search Engineer',
      'Associate Sales Representative',
      'Director, User Data Products',
      'LAMP Developer',
      'Sr. IOS Developer',
      'Sr. Android Developer',
      'Sr. Java Software Engineer',
      'Sr. Project Manager',
      'Digital Art Director',
      'Technical Recruiter',
      'Business Operations',
      'Product Designer - Venmo',
      'Android Engineer',
      'Engineering Internship - NYC',
      'Growth Engineer',
      'Internal Tools Engineering Lead',
      'iOS Engineer - New York',
      'Senior Data Engineer',
      'Software Engineer',
      'Systems Engineer',
      'Web Engineer',
      'Manager, Mobile API Growth',
      'Mobile Developer',
      'Mobile Developer (Intern)',
      'Business Development',
      'Business Development (Intern)',
      'Translation Coordinator ',
      'Communications Manager',
      'Communications Assistant ',
      'Production and Circulation Manager ',
      'Creative',
      'Project Budget Assistant ',
      'Sales Representative ',
      'Accounts Payable Assistant',
      'Java Developer (Front-end)',
      'Ad Ops Campaign Manager',
      'Front-End Mobile Web Developer (Front-End Engineer)',
      'Lead Mobile Android Engineer',
      'Sr. MySQL Database Engineer',
      'Intern - Rewards',
      'Manager, Integrated Marketing Solutions',
      'Sales Planner',
      'Digital Strategist, DSP/Trading Desk - Programmatic (NYC)',
      'Sales Planner',
      'Digital Media Analyst, DSP/Trading Desk - Programmatic (NYC)',
      'Account Director',
      'Account Executive',
      'Account Lead',
      'Analyst',
      'Community Manager',
      'Designer',
      'Group Director',
      'Media Manager',
      'Micro-Content Producer',
      'Senior Interface Engineer',
      'Summer Interns',
      'Project Manager',
      'Senior Business Development Executive',
      'Business Development Executive',
      'Strategic Account Manager',
      'Account Manager',
      'Sales Lead',
      'Curator',
      'Open Ended',
      'Head of Marketing',
      'Growth Hacker',
      'Front End Architect',
      'Mobile Application Architect',
      'Data Scientist',
      'Recruiter and HR Specialist ',
      'Experienced Licensed Real Estate Salesperson/Associate Broker',
      'Campus Ambassador',
      'Lead Perks Production Coordinator',
      'Customer Service Coordinator',
      'Editorial Assistant',
      'NYC Staff Writer',
      'Software Engineer, Front-End',
      'Editorial/Reporting Internship, Spring 2014',
      'Spring 2014 Internship',
      'Account Manager',
      'Marketing Manager',
      'Ad Operations Associate',
      'Perks Sales Manager',
      'Marketing Internship',
      'Business Development Team Internship',
      'Sustainability Internship',
      'Legal Internship',
      'PR and Communications',
      'Developer Operations Engineer',
      'Accounting Intern',
      'Business Development Representative',
      'Enterprise Sales Executive',
      'Sales Engineer',
      'Director of Engineering, Applications',
      'Jr. Applications Developer',
      'Sr. Applications Developer',
      'Account Manager',
      'Social Media Buyer',
      'Senior Engineer - Web',
      'Customer Support Associate',
      'Marketing Director',
      'Mobile Apps Engineer',
      'Merchandise Planning Analyst',
      'HR Director',
      'Senior Planner',
      'Purchasing Intern',
      'Drop Ship Intern',
      'Assistant Merchandise Coordinator',
      'Graphic Designer',
      'Senior Copywriter',
      'Copywriter',
      'Photography Intern',
      'Graphic Designer Intern',
      'Analyst, Data Science',
      'Public Relations Intern',
      'Customer Service Supervisor',
      'Operations Staffing Intern',
      'Software Developer Intern',
      'Executive Assistant',
      'Human Resources Manager of Recruiting',
      'Merchandising Director/Head Buyer',
      'Associate Buyer',
      'Buyer',
      'Assistant Buyer',
      'Merchandising Intern',
      'Graphic Designer - Product Development',
      'Assistant Production Manager',
      'Slotting Intern',
      'Operations Data/Process Analyst Intern',
      'Technical Account Manager / Client Solutions Engineer',
      'Account Executive/Sales Director',
      'UI Engineer',
      'Marketing Manager',
      'Web Services Engineer',
      'Webserver Engineer',
      'MBA Intern, Business Development',
      'Production Designer',
      'Android Engineer',
      'API Engineer',
      'Data Center Technician',
      'Director of Site Reliability ( SRE )',
      'Engineering Summer Intern',
      'Front-End Product Engineer',
      'iOS Engineer/Mobile Developer (iOS)',
      'MySQL Engineer',
      'PHP Application Engineer',
      'Search & Discovery: Data Scientist',
      'Search & Discovery: Software Engineer',
      'Site Reliability Engineer',
      'Trust & Safety Manager',
      'Senior Engineering Recruiter',
      'Brand Strategist, New York',
      'Software Developer',
      'QA Automation/Deployment Engineer',
      'Tools/Platform Developer',
      'Account Executive',
      'Account Manager, Publisher Development',
      'Analyst, Advertising Operations',
      'Controller',
      'Software Developer',
      'Customer Service Case Manager',
      'Senior Linux System Administrator',
      'Senior Product Manager',
      'Senior Software Engineer – Integration Architecture',
      'Senior Software Engineer',
      'Software Engineer',
      'Systems Analyst',
      'Intern',
      'User Interface Developer',
      'Java Algorithm Developer',
      'Server Side Developer',
      'Junior Product Design Engineer',
      'Tomorrow Lab Internship',
      'Client Services Specialist',
      'Frontend developer - Junior',
      'QA Engineer',
      'Sales Engineer',
      'Senior Web Software Engineer',
      'Web Software Engineer',
      'Events Coordinator',
      'Sales Marketing Associate',
      'Ad Operations Coordinator',
      'Events & Promotions Intern',
      'Director, Strategic Analytics',
      'PR Intern',
      'Communications Coordinator',
      'Design Intern',
      'Graphic Designer',
      'Editorial Internship',
      'Staff Writer',
      'Style Editor',
      'Accounts Payable Inventory Specialist',
      'Accounts Payable Specialist',
      'Recruiter',
      'Photographer',
      'Photo Stylist',
      'Editor',
      'Lifestyle Product Editor',
      'Sr. Manager, Customer Acquisition',
      'Social Media Coordinator',
      'Retention Coordinator',
      'Assistant Merchandise Planner',
      'Sr. Digital Analyst',
      'Business Analyst',
      'Studio Planning Intern',
      'Studio Prepper',
      'Product Photographer',
      'Soft Goods Stylist',
      'Studio Assistant',
      'Studio Production Assistant',
      'Shops Editor',
      'Interface Developer',
      'iOS Developer',
      'Web Applications Developer',
      'Junior Product Manager',
      'MySQL DBA',
      'Developer',
      'Director of Product',
      'Director of Engineering',
      'Account Executive',
      'Head of Marketing',
      'Graphic Designer',
      'Business Analyst, MBA Intern',
      'Product Intern',
      'Marketing Intern',
      'Paid Marketing Manager',
      'Communications & Social Media Manager',
      'Engineering',
      'Front End Web Development Mentor',
      'Python Mentor',
      'Ruby on Rails Mentor',
      'iOS Development Mentor',
      'Product Specialist',
      'M&A Reporter',
      'Bankruptcy reporter',
      'Social Media Coordinator',
      'Temporary Part-Time Customer Service Representative',
      'Senior Editorial Research Coordinator',
      'SEO Associate',
      'Director of Analytics & Consumer Insights',
      'Systems Administrator',
      'Senior Data Coordinator',
      'Email Marketing Manager',
      'Digital Journalist',
      'Senior Software Engineer',
      'Senior Architect',
      'Business Development Manager',
      'Front End Developer',
      'Software Engineer',
      'iOS Developer',
      'Interaction Designer',
      'Art Director - Product/UX',
      'Product Manager',
      'Inside Sales Manager',
      'Account Executive',
      'Account Manager',
      'Manager, PR',
      'CRM Manager',
      'Software Engineer',
      'Community Manager',
      'Freelance/Junior Web Designer',
      'Director, Children’s Video Distribution (New York, NY)',
      'Senior Software Engineer (New York, NY)',
      'Corporate Marketing Coordinator (New York, NY)',
      'MCN Team Intern',
      'Content Management Intern',
      'Interactive Marketing Internship',
      'Retail Marketing Internship',
      'Corporate Marketing Internship',
      'Client Services Internship',
      'Video Operations Internship',
      'Film Distribution Internship',
      'Licensing and Creative Services Internship',
      'Operations Internship',
      'Physical Distribution Internship',
      'Graphic Design Internship',
      'Senior Editor',
      'Executive & Operational Assistant',
      'Advertising & Sales Internship',
      'Internship',
      'Associate Project Manager',
      'Developer',
      'Jr. Developer',
      'iOS Developer',
      'Office Manager',
      'Event Technician',
      'Office Intern',
      'Software Development Intern',
      'SOCIAL MEDIA SOFTWARE DEVELOPER',
      'WEB DEVELOPER',
      'FRONT END WEB DEVELOPER',
      'Product Outreach: Community & Partnerships',
      'DevOps Engineer',
      'Lead Server Engineer',
      'Web Developer',
      'Director of Talent and Development',
      'Assistant to the TED Partnership Development Team',
      'Creative Partner Coordinator',
      'Graphic Designer',
      'Media Planner',
      'Product Development Manager',
      'TED Prize Storyteller',
      'TEDx Special Projects Intern',
      'iOS Developer – Full Time',
      'Operations Manager – Full Time',
      'Project Manager – Full Time',
      'Web Development Intern',
      'Graphics Intern',
      'Business Development - Product Partnerships',
      'Data Engineer',
      'Data Scientist',
      'Director of Financial Reporting and Analysis',
      'Director of Solutions Consulting',
      'Enterprise Project Manager',
      'Front-End Engineer',
      'Publisher Sales',
      'SaaS User Experience Designer / Visual Designer',
      'Senior Director, Statistician',
      'Senior Solutions Consulting',
      'Senior Solutions Engineer',
      'Software Engineer',
      'Supply Analyst',
      'Technical Account Manager',
      'Technical Analyst',
      'Yield Analyst',
      'Junior Rails Developer',
      'Customer Success Specialist',
      'Senior Account Executive',
      'Tech PR Manager (Full-time)',
      'Fashion PR Manager (Part-time / Freelance)',
      'Account Manager Assistant - Fashion (Internship)',
      'Account Manager Assistant - Beauty (Internship)',
      'Account Manager Assistant - Tech (Internship)',
      'Motion Graphic Designer (Internship)',
      'Video Editor Assistant (Internship)',
      'Graphic Design (Intership)',
      'Engineer',
      'Manager, Network Development',
      'Creative Technologist',
      'Field Producer',
      'Stylitics Ambassador',
      'Editor, Beauty High',
      'Developer',
      'Managing Editor',
      'Senior Web & UI Designer',
      'Social Media',
      'Analytics',
      'Technology',
      'Sales & Marketing',
      'Graphic Design',
      'Beauty Editorial',
      'Style & Lifestyle Editorial',
      'New Business Manager',
      'SENIOR INTERACTION DESIGNER',
      'FRONT END DEVELOPER',
      'INTERNSHIP: INTERACTION DESIGNER',
      'Intern',
      'Partnership Associate',
      'Ad Solutions Manager (New York)',
      'Senior Director/Director of Marketing - StreetEasy',
      'Senior Design and UX Lead - StreetEasy',
      'Head of Talent & Culture',
      'Client Development Manager',
      'Process Management Analyst',
      'Graphic Design Director',
      'Account Coordinator',
      'Sales Director',
      'Software Engineer',
      'Senior Sysop Engineer',
      'Creative Developer',
      'Dev Ops',
      'Intermediate PHP/Web Developer',
      'Full-Stack Web Developer',
      'Community Manager (bilingual English/Japanese)',
      'Global Payroll Manager',
      'Production Designer',
      'Template Developer',
      'Android Developer',
      'Network Engineer',
      'Network Engineer - Commerce',
      'Software Engineer - Data Team',
      'Software Engineer - Front End',
      'Software Engineer - Platform',
      'Software Engineer - Product',
      'Business Intelligence Analyst',
      'Business Intelligence Analyst',
      'Director, Business Development',
      'Director, Data Analytics',
      'Events Coordinator',
      'HR Operations and Technology Lead',
      'Senior Technical Recruiter',
      'Product Designer',
      'Full-Stack Web Engineer',
      'Junior Developer Internship',
      'PART-TIME SALES COORDINATOR',
      'FREELANCE SOCIAL MEDIA STRATEGIST',
      'DEVELOPERS WANTED',
      'Front End Web Developer',
      'Database Developer',
      'System Administrator',
      'Software Engineer',
      'Senior Software Engineer (PHP)',
      'QA Automation Engineer',
      'Front End Developer',
      'Python / Django Intern',
      'Publishing Operations Coordinator',
      'Publishing Operations Intern',
      'Counterpoint Intern',
      'Digital Marketing Intern',
      'QA Manager',
      '.NET App Developer',
      'Front-End Web Developer',
      'Director / Account Manager',
      'Android Development Lead',
      'iOS Engineer',
      'Infrastructure-ish Engineer',
      'Regional Sales Managers (New York, Chicago, Toronto)',
      'Ad Trafficker',
      'Yield Optimization Manager',
      'Account Manager',
      'Web Developer',
      'Systems Operations Engineer',
      'Java Engineer',
      'Public Relations Director',
      'Quality Assurance Engineer',
      'Data Scientist, R&D',
      'SENIOR APPLICATION UX & DESIGN LEAD',
      'SALES ACCOUNT EXECUTIVE',
      'ACCOUNT MANAGER',
      'Quantitative Analyst',
      'Junior Web Developer',
      'Growth Hacker Product Manager',
      'Product Manager',
      'Android Developer',
      'Junior Linux Systems Administrator',
      'iOS Engineer',
      'Insights Manager (New York City)',
      'Sales Development Manager',
      'Internship – Community Management Intern',
      'VP, Business Development',
      'QA Developer',
      'Senior Software Developer ',
      'Software Developer',
      'Editorial Intern',
      'Personal Finance Writer',
      'Data Analyst Intern',
      'Senior Product Manager',
      'Web Designer',
      'Senior Sales Engineer',
      'Enterprise Account Executive',
      'Product Marketing Manager',
      'Channel Marketing Manager',
      'Specialist, Website & SEO',
      'Marketing Automation Specialist',
      'Channel Sales',
      'Sr. Java Developer',
      'Infrastructure Development / DevOps Engineer',
      'Information Security Operations Engineer',
      'Client Services Manager',
      'Technical Support Manager',
      'Translation Services Manager',
      'VP Finance',
      'Client Services Intern',
      'Content & Communications Intern',
      'Creative Content Supervisor',
      'Creative Strategy Intern',
      'Design Intern',
      'Freelance Designer',
      'Freelance Flash Designer',
      'IT Intern',
      'Junior Video Editor',
      'Media Intern',
      'New Business Intern',
      'Part Time Billing Assistant',
      'Project Management Intern',
      'Senior Account Executive',
      'Senior Interactive Designer',
      'Desktop and Server Support - Field and Remote Technician',
      'SOFTWARE ENGINEER',
      'QA ENGINEER',
      'INSIDE SALES CONSULTANT',
      'Full-Stack Marketer (Growth)',
      'Head of Communications & PR',
      'Category Manager (Growth)',
      'Recruiter',
      'Engineer',
      'Front-End Engineer',
      'Content Education Producer',
      'VP of Engineering',
      'General Manager',
      'Content Acquisition Editor',
      'Community Manager (Support)',
      'Product Designer',
      'Internship',
      'Senior UI/UX Designer',
      'Senior Software Engineer - Big Data',
      'Lead Platform Architect',
      'Senior Software Engineer - Web Applications',
      'Sr Operations Engineer',
      'Advertising Operations Manager',
      'Advertising Sales Executive',
      'DIGITAL MERCHANDISING SPECIALIST',
      'INTERN',
      'UI DEVELOPER',
      'SOFTWARE ENGINEER',
      'PRODUCT MANAGER',
      'ACCOUNT MANAGER',
      'SALES ASSOCIATE',
      'Software Engineer',
      'ENGINEERS',
      'DATA SCIENTISTS',
      'DESIGNERS',
      'ACCOUNT SERVICES',
      'INTERNS',
      'Account Specialist',
      'Sales Director',
      'Director of Product Management',
      'Front End Web Developer',
      'Front end engineer',
      'Ruby on Rails Engineer',
      'Talented Generalist Engineer',
      'iOS Developer',
      'Director of Marketing',
      'Jr Online Marketing Analyst',
      'Product Manager - Conversion and On-Boarding Experience',
      'Product Manager - Handheld Apps',
      'Senior Director of Platform Products',
      'Visual Interaction Designer',
      'Customer Care Advisor',
      'eCommerce Associate',
      'WEB  DEVELOPER',
      'LEAD  IX  DESIGNER',
      'LEAD  iOS  DEVELOPER',
      'Sales Representative',
      'Internship',
      'Photography Internship',
      'Software Engineer',
      'UI Team Lead',
      'Engineering Team Lead',
      'Senior Database Engineer',
      'Head of Communications',
      'Community Outreach Coordinator',
      'Accounting & Finance Intern (part-time)',
      'Account Manager (AEC/SaaS)',
      'Lead UX Designer',
      'Regional Sales Manager (AEC/SaaS)',
      'Scala Developer for Green Building Software',
      'Sustainable Building Design Engineer / Architect',
      'Sustainable Building Design Engineer / Architect',
      'Software Engineer, Hadoop/Data team',
      'Software Engineer (Python)',
      'Quality Assurance (QA) Lead',
      'Interactive Project Manager',
      'Inside Sales Associate',
      'Sales Executive',
      'iOS Developer',
      'Android Developer',
      'Operations Engineer',
      'Frontend Developer',
      'Web Engineer',
      'Web & Mobile Designer',
      'Marketing Intern',
      'Sports Analyst Intern',
      'Marketing Associate',
      'Marketing Director - Bitcoin Investment Trust',
      'Account Executive',
      'Inside Sales Associate - Bitcoin Investment Trust',
      'Outside Sales Executive - Bitcoin Investment Trust',
      'Lead IOS Engineer',
      'Lead Server Side Engineer',
      'Design Intern',
      'Senior Web Application Developer',
      'Full Stack Software Engineer, Full-time',
      'Senior Account Executive',
      'Data Management Internship',
      'Social Media & SEO Intern',
      'Sr. Web Application Engineer',
      'Software Engineer - Mobile Application Development',
      'Database Administrator and Developer',
      'Paid Marketing Interns',
      'Infrastructure Architect',
      'Software Engineer (Web)',
      'Systems Engineer',
      'Product Manager, API & Integrations',
      'UI/UX Designer',
      'Account Executive (Bilingual Spanish) ',
      'Account Executives',
      'Conferences and Events Manager',
      'Client Success Manager',
      'Tech Recruiter' 
    ]
  end
  
end
